name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Build app
        working-directory: client
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_DUNE_0D55F9410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "client/dist"
          api_location: ""
          output_location: ""
          skip_app_build: true
